<?php

namespace ArcaSolutions\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ControlExportListingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlExportListingRepository extends EntityRepository
{
}
