<?php

namespace ArcaSolutions\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CronLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronLogRepository extends EntityRepository
{
}
