<?php

namespace ArcaSolutions\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends EntityRepository
{
}
