<?php

namespace ArcaSolutions\CoreBundle\Repository;

use ArcaSolutions\CoreBundle\Interfaces\EntityCategoryRepositoryInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * BaseModule
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityCategoryRepository extends EntityRepository implements EntityCategoryRepositoryInterface
{

    /**
     * @var int Default 20
     */
    protected $max_items;

    /**
     * {@inheritdoc}
     */
    public function getParentCategories($featured = true)
    {
        $q = $this->createQueryBuilder('q')
            ->where('q.categoryId IS NULL')
            ->andWhere('q.featured = :featured')
            ->andWhere('q.enabled = :enabled')
            ->setParameter('featured', $featured ? 'y' : 'n')
            ->setParameter('enabled', 'y')
            ->orderBy('q.title', 'ASC');

        if (is_int($this->max_items)) {
            $q->setMaxResults($this->max_items);
        }

        return $q->getQuery()->getResult();
    }

    public function getAllParent()
    {
        return $this->createQueryBuilder('c')
            ->where('c.categoryId IS  NULL')
            ->andWhere('c.enabled = :enabled')
            ->setParameter(':enabled', 'y')
            ->getQuery()
            ->getResult();
    }

    /**
     * Get the list of categories with all children, following the deepth level passed by param
     * @param int|null $parentId Represents the link(category_id)
     * @param int $deepthLevel How deep you want the hierarchy
     * @param int $level It is for internal use
     * @return array
     */
    public function getHierarchyCategories($parentId = null, $deepthLevel = -1, $level = 0)
    {
        if ($deepthLevel > -1 && ($level > $deepthLevel)) {
            return;
        }

        $categories = $this->createQueryBuilder('c')
            ->orderBy('c.title', 'ASC')
            ->where('c.enabled = :enabled')
            ->setParameter(':enabled', 'y');

        if (is_int($parentId) and 0 !== $parentId) {
            $categories->andWhere('c.categoryId = :category')
                ->setParameter('category', $parentId);
        } else {
            $categories->andWhere('c.categoryId IS NULL');
        }

        $categories = $categories->getQuery()
            ->getResult();

        $level++;
        foreach ($categories as &$category) {
            $category->setChildren($this->getHierarchyCategories($category->getId(), $deepthLevel, $level));
        }

        return $categories;
    }

    /**
     * Returns the quantity of categories
     * @return int
     * @throws Query\QueryException
     */
    public function getCategoriesCount()
    {
        return $this->createQueryBuilder('c')
            ->select('count(c.id)')
            ->where('c.enabled = :enabled')
            ->setParameter(':enabled', 'y')
            ->getQuery()
            ->getSingleScalarResult();
    }


    /**
     * Returns the quantity of featured categories
     * @return int
     * @throws Query\QueryException
     */
    public function getCategoriesFeaturedCount()
    {
        return $this->createQueryBuilder('c')
            ->select('count(c.id)')
            ->andWhere('c.featured = :featured')
            ->andWhere('c.enabled = :enabled')
            ->setParameter(':enabled', 'y')
            ->setParameter(':featured', 'y')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @return mixed
     */
    public function getMaxItems()
    {
        return $this->max_items;
    }

    /**
     * @param mixed $max_items
     */
    public function setMaxItems($max_items)
    {
        if (is_int($max_items)) {
            $this->max_items = $max_items;
        }
    }
}
