<?php

namespace ArcaSolutions\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Location1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Location1Repository extends EntityRepository
{
}
