<?php

namespace ArcaSolutions\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PackagemodulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackagemodulesRepository extends EntityRepository
{
}
