<?php

namespace ArcaSolutions\ClassifiedBundle\Repository;

use ArcaSolutions\CoreBundle\Repository\EntityCategoryRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * Classifiedcategory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifiedcategoryRepository extends EntityCategoryRepository
{
    /**
     * ClassifiedcategoryRepository constructor.
     * Sets active items field
     *
     * @param EntityManager $em
     * @param ClassMetadata $class
     */
    public function __construct(EntityManager $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);

    }

    /**
     * {@inheritdoc}
     */
    public function getParentCategories($limit = null, $featured = true)
    {
        $this->setMaxItems($limit);

        return parent::getParentCategories($featured);
    }

    /**
     * @param int $limit
     *
     * @return array
     */
    public function getPopularCategories($limit = null)
    {
        return $this->createQueryBuilder('q')
            ->andWhere('q.enabled = :enabled')
            ->setParameter('enabled', 'y')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
