<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160711153027 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE Banner DROP suspended_sitemgr, CHANGE random_number random_number BIGINT DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE Article DROP suspended_sitemgr, CHANGE cat_3_id cat_3_id INT DEFAULT NULL, CHANGE cat_5_id cat_5_id INT DEFAULT NULL, CHANGE cat_4_id cat_4_id INT DEFAULT NULL, CHANGE cat_1_id cat_1_id INT DEFAULT NULL, CHANGE cat_2_id cat_2_id INT DEFAULT NULL, CHANGE random_number random_number BIGINT DEFAULT \'0\' NOT NULL, CHANGE parcat_1_level1_id parcat_1_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_1_level2_id parcat_1_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_1_level3_id parcat_1_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_1_level4_id parcat_1_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level1_id parcat_2_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level2_id parcat_2_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level3_id parcat_2_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level4_id parcat_2_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level1_id parcat_3_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level2_id parcat_3_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level3_id parcat_3_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level4_id parcat_3_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level1_id parcat_4_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level2_id parcat_4_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level3_id parcat_4_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level4_id parcat_4_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level1_id parcat_5_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level2_id parcat_5_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level3_id parcat_5_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level4_id parcat_5_level4_id INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE Classified DROP zip5, DROP maptuning, DROP maptuning_date, DROP suspended_sitemgr, CHANGE cat_3_id cat_3_id INT DEFAULT NULL, CHANGE cat_5_id cat_5_id INT DEFAULT NULL, CHANGE cat_4_id cat_4_id INT DEFAULT NULL, CHANGE cat_1_id cat_1_id INT DEFAULT NULL, CHANGE cat_2_id cat_2_id INT DEFAULT NULL, CHANGE random_number random_number BIGINT DEFAULT \'0\' NOT NULL, CHANGE parcat_1_level1_id parcat_1_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_1_level2_id parcat_1_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_1_level3_id parcat_1_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_1_level4_id parcat_1_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level1_id parcat_2_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level2_id parcat_2_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level3_id parcat_2_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level4_id parcat_2_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level1_id parcat_3_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level2_id parcat_3_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level3_id parcat_3_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level4_id parcat_3_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level1_id parcat_4_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level2_id parcat_4_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level3_id parcat_4_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level4_id parcat_4_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level1_id parcat_5_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level2_id parcat_5_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level3_id parcat_5_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level4_id parcat_5_level4_id INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE Event CHANGE start_time start_time TIME DEFAULT NULL, CHANGE end_time end_time TIME DEFAULT NULL');
        /* Custom SQL */
        $this->addSql('UPDATE Event SET start_time = NULL WHERE has_start_time <> \'y\'');
        $this->addSql('UPDATE Event SET end_time = NULL WHERE has_end_time <> \'y\'');
        /**************/
        $this->addSql('ALTER TABLE Event DROP has_start_time, DROP has_end_time, DROP zip5, DROP maptuning, DROP maptuning_date, DROP suspended_sitemgr, CHANGE cat_3_id cat_3_id INT DEFAULT NULL, CHANGE cat_5_id cat_5_id INT DEFAULT NULL, CHANGE cat_4_id cat_4_id INT DEFAULT NULL, CHANGE cat_1_id cat_1_id INT DEFAULT NULL, CHANGE cat_2_id cat_2_id INT DEFAULT NULL, CHANGE importID importID INT DEFAULT NULL, CHANGE random_number random_number BIGINT DEFAULT \'0\' NOT NULL, CHANGE parcat_1_level1_id parcat_1_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_1_level2_id parcat_1_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_1_level3_id parcat_1_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_1_level4_id parcat_1_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level1_id parcat_2_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level2_id parcat_2_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level3_id parcat_2_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_2_level4_id parcat_2_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level1_id parcat_3_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level2_id parcat_3_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level3_id parcat_3_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_3_level4_id parcat_3_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level1_id parcat_4_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level2_id parcat_4_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level3_id parcat_4_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_4_level4_id parcat_4_level4_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level1_id parcat_5_level1_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level2_id parcat_5_level2_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level3_id parcat_5_level3_id INT DEFAULT 0 NOT NULL, CHANGE parcat_5_level4_id parcat_5_level4_id INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE Listing DROP maptuning, DROP maptuning_date, DROP suspended_sitemgr');
        $this->addSql('ALTER TABLE Listing_Summary CHANGE random_number random_number BIGINT DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE Listing_FeaturedTemp CHANGE random_number random_number BIGINT NOT NULL');
        $this->addSql('ALTER TABLE Promotion DROP listing_zip5');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

	$this->addSql('SET FOREIGN_KEY_CHECKS=0');

        $this->addSql('ALTER TABLE Article ADD suspended_sitemgr VARCHAR(1) NOT NULL, CHANGE cat_1_id cat_1_id INT NOT NULL, CHANGE cat_2_id cat_2_id INT NOT NULL, CHANGE cat_3_id cat_3_id INT NOT NULL, CHANGE cat_4_id cat_4_id INT NOT NULL, CHANGE cat_5_id cat_5_id INT NOT NULL, CHANGE random_number random_number BIGINT NOT NULL, CHANGE parcat_1_level1_id parcat_1_level1_id INT NOT NULL, CHANGE parcat_1_level2_id parcat_1_level2_id INT NOT NULL, CHANGE parcat_1_level3_id parcat_1_level3_id INT NOT NULL, CHANGE parcat_1_level4_id parcat_1_level4_id INT NOT NULL, CHANGE parcat_2_level1_id parcat_2_level1_id INT NOT NULL, CHANGE parcat_2_level2_id parcat_2_level2_id INT NOT NULL, CHANGE parcat_2_level3_id parcat_2_level3_id INT NOT NULL, CHANGE parcat_2_level4_id parcat_2_level4_id INT NOT NULL, CHANGE parcat_3_level1_id parcat_3_level1_id INT NOT NULL, CHANGE parcat_3_level2_id parcat_3_level2_id INT NOT NULL, CHANGE parcat_3_level3_id parcat_3_level3_id INT NOT NULL, CHANGE parcat_3_level4_id parcat_3_level4_id INT NOT NULL, CHANGE parcat_4_level1_id parcat_4_level1_id INT NOT NULL, CHANGE parcat_4_level2_id parcat_4_level2_id INT NOT NULL, CHANGE parcat_4_level3_id parcat_4_level3_id INT NOT NULL, CHANGE parcat_4_level4_id parcat_4_level4_id INT NOT NULL, CHANGE parcat_5_level1_id parcat_5_level1_id INT NOT NULL, CHANGE parcat_5_level2_id parcat_5_level2_id INT NOT NULL, CHANGE parcat_5_level3_id parcat_5_level3_id INT NOT NULL, CHANGE parcat_5_level4_id parcat_5_level4_id INT NOT NULL');
        $this->addSql('ALTER TABLE Banner ADD suspended_sitemgr VARCHAR(1) NOT NULL, CHANGE random_number random_number BIGINT NOT NULL');
        $this->addSql('ALTER TABLE Classified ADD zip5 VARCHAR(10) NOT NULL, ADD maptuning VARCHAR(255) NOT NULL, ADD maptuning_date DATETIME NOT NULL, ADD suspended_sitemgr VARCHAR(1) NOT NULL, CHANGE cat_1_id cat_1_id INT NOT NULL, CHANGE cat_2_id cat_2_id INT NOT NULL, CHANGE cat_3_id cat_3_id INT NOT NULL, CHANGE cat_4_id cat_4_id INT NOT NULL, CHANGE cat_5_id cat_5_id INT NOT NULL, CHANGE random_number random_number BIGINT NOT NULL, CHANGE parcat_1_level1_id parcat_1_level1_id INT NOT NULL, CHANGE parcat_1_level2_id parcat_1_level2_id INT NOT NULL, CHANGE parcat_1_level3_id parcat_1_level3_id INT NOT NULL, CHANGE parcat_1_level4_id parcat_1_level4_id INT NOT NULL, CHANGE parcat_2_level1_id parcat_2_level1_id INT NOT NULL, CHANGE parcat_2_level2_id parcat_2_level2_id INT NOT NULL, CHANGE parcat_2_level3_id parcat_2_level3_id INT NOT NULL, CHANGE parcat_2_level4_id parcat_2_level4_id INT NOT NULL, CHANGE parcat_3_level1_id parcat_3_level1_id INT NOT NULL, CHANGE parcat_3_level2_id parcat_3_level2_id INT NOT NULL, CHANGE parcat_3_level3_id parcat_3_level3_id INT NOT NULL, CHANGE parcat_3_level4_id parcat_3_level4_id INT NOT NULL, CHANGE parcat_4_level1_id parcat_4_level1_id INT NOT NULL, CHANGE parcat_4_level2_id parcat_4_level2_id INT NOT NULL, CHANGE parcat_4_level3_id parcat_4_level3_id INT NOT NULL, CHANGE parcat_4_level4_id parcat_4_level4_id INT NOT NULL, CHANGE parcat_5_level1_id parcat_5_level1_id INT NOT NULL, CHANGE parcat_5_level2_id parcat_5_level2_id INT NOT NULL, CHANGE parcat_5_level3_id parcat_5_level3_id INT NOT NULL, CHANGE parcat_5_level4_id parcat_5_level4_id INT NOT NULL');
        $this->addSql('ALTER TABLE Event CHANGE start_time start_time TIME NOT NULL, CHANGE end_time end_time TIME NOT NULL');
        /* Custom SQL */
        $this->addSql('UPDATE Event SET start_time = \'0000-00-00\' WHERE has_start_time = \'y\'');
        $this->addSql('UPDATE Event SET end_time = \'0000-00-00\' WHERE has_end_time = \'y\'');
        /**************/
        $this->addSql('ALTER TABLE Event ADD has_start_time VARCHAR(1) NOT NULL, ADD has_end_time VARCHAR(1) NOT NULL, ADD zip5 VARCHAR(10) NOT NULL, ADD maptuning VARCHAR(255) NOT NULL, ADD maptuning_date DATETIME NOT NULL, ADD suspended_sitemgr VARCHAR(1) NOT NULL, CHANGE cat_1_id cat_1_id INT NOT NULL, CHANGE cat_2_id cat_2_id INT NOT NULL, CHANGE cat_3_id cat_3_id INT NOT NULL, CHANGE cat_4_id cat_4_id INT NOT NULL, CHANGE cat_5_id cat_5_id INT NOT NULL, CHANGE importID importID INT NOT NULL, , CHANGE random_number random_number BIGINT NOT NULL, CHANGE parcat_1_level1_id parcat_1_level1_id INT NOT NULL, CHANGE parcat_1_level2_id parcat_1_level2_id INT NOT NULL, CHANGE parcat_1_level3_id parcat_1_level3_id INT NOT NULL, CHANGE parcat_1_level4_id parcat_1_level4_id INT NOT NULL, CHANGE parcat_2_level1_id parcat_2_level1_id INT NOT NULL, CHANGE parcat_2_level2_id parcat_2_level2_id INT NOT NULL, CHANGE parcat_2_level3_id parcat_2_level3_id INT NOT NULL, CHANGE parcat_2_level4_id parcat_2_level4_id INT NOT NULL, CHANGE parcat_3_level1_id parcat_3_level1_id INT NOT NULL, CHANGE parcat_3_level2_id parcat_3_level2_id INT NOT NULL, CHANGE parcat_3_level3_id parcat_3_level3_id INT NOT NULL, CHANGE parcat_3_level4_id parcat_3_level4_id INT NOT NULL, CHANGE parcat_4_level1_id parcat_4_level1_id INT NOT NULL, CHANGE parcat_4_level2_id parcat_4_level2_id INT NOT NULL, CHANGE parcat_4_level3_id parcat_4_level3_id INT NOT NULL, CHANGE parcat_4_level4_id parcat_4_level4_id INT NOT NULL, CHANGE parcat_5_level1_id parcat_5_level1_id INT NOT NULL, CHANGE parcat_5_level2_id parcat_5_level2_id INT NOT NULL, CHANGE parcat_5_level3_id parcat_5_level3_id INT NOT NULL, CHANGE parcat_5_level4_id parcat_5_level4_id INT NOT NULL');
        $this->addSql('ALTER TABLE Listing ADD maptuning VARCHAR(255) DEFAULT NULL, ADD maptuning_date DATETIME DEFAULT NULL, ADD suspended_sitemgr VARCHAR(1) DEFAULT \'n\' NOT NULL');
        $this->addSql('ALTER TABLE Listing_FeaturedTemp CHANGE random_number random_number BIGINT NOT NULL');
        $this->addSql('ALTER TABLE Listing_Summary CHANGE random_number random_number BIGINT NOT NULL');
        $this->addSql('ALTER TABLE Promotion ADD listing_zip5 VARCHAR(10) NOT NULL');

	$this->addSql('SET FOREIGN_KEY_CHECKS=1');
    }
}
