<?php

namespace ArcaSolutions\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SettingLocationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SettingLocationRepository extends EntityRepository
{
    /**
     * Returns ids of enabled locations
     *
     * @param bool $excludeNoShow
     * @return array
     */
    public function getLocationsEnabledID($excludeNoShow = true, $parent = false)
    {
        $conditions = [
            'enabled' => 'y'
        ];

        $excludeNoShow and $conditions["show"] = "b";

        $locations = $this->findBy(
            $conditions,
            ['id' => 'ASC']
        );

        $ids = [];
        foreach ($locations as $loc) {
            if (($parent && $loc->getId() > $parent) || !$parent)
                $ids[] = $loc->getId();
        }

        return $ids;
    }

    public function getLastLocationEnabledID()
    {
        $location = $this->findOneBy(['enabled' => 'y'], ['id' => 'DESC']);

        if ($location) {
            return $location->getId();
        }

        return null;
    }
}
