sensio_framework_extra:
    view:
        annotations: false

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: ^/api, priorities: ['json', 'html', '*/*'], fallback_format: json, prefer_extension: true }
            - { path: ^/, stop: true }
    body_converter:
        enabled: true
        validate: true
    view:
        view_response_listener: 'force'
        exception_wrapper_handler: ArcaSolutions\ApiBundle\Handler\ExceptionWrapperHandler
        formats:
            json: true
            xml: false
        templating_formats:
            html: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Symfony\Component\HttpKernel\Exception\HttpException': true
        enabled: true
    access_denied_listener:
        json: true
    disable_csrf_role: ROLE_API

nelmio_api_doc:
    name: "eDirectory API"
