imports:
    - { resource: parameters.yml }
    - { resource: domain.yml }
    - { resource: security.yml }
    - { resource: database.yml }
    - { resource: search.yml }
    - { resource: pagination.yml }
    - { resource: api.yml }

framework:
    #esi:             ~
    default_locale: "%locale%"
    translator:
        fallback: "en"
        enabled: true
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # It makes symfony's session works with php's session instead of its owner (We use it to get info about sitemgr)
        save_path: ~
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool:      { type: memory }

twig:
    strict_variables: false
    cache:            "%kernel.cache_dir%/twig"
    charset:          "%kernel.charset%"
    debug:            "%kernel.debug%"
    form:
        resources:
            - 'CoreBundle:Form:fields.html.twig'


assetic:
    debug: '%kernel.debug%'
    bundles: {  }
    filters:
        cssrewrite: null
        lessphp:
            file: '%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php'
            apply_to: \.less$
            formatter: compressed
            preserve_comments: false
            sourcemap: true

# Twig Extensions
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

liip_theme:
    themes:
        - default
        - doctor
        - restaurant
        - wedding
    active_theme: default
    assetic_integration: true
    load_controllers: false
    path_patterns:
        app_resource:
            - '%%app_path%%/custom/%%current_theme%%/%%template%%'
        bundle_resource:
            - '%%bundle_path%%/custom/%%current_theme%%/%%bundle_name%%/%%template%%'
        bundle_resource_dir:
            - '%%dir%%/custom/%%current_theme%%/%%bundle_name%%/%%template%%'

# Thumbnails Configuration
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.root_dir%/../web'
    filter_sets:
        cache: null
        small:
           quality: 100
           filters:
               thumbnail:
                   size:
                       - 400
                       - 300
                   mode: inset
        noimage:
            quality: 90
            filters:
                thumbnail:
                    size:
                        - 200
                        - 150
                    mode: inset
                background:
                    size:
                        - 400
                        - 300
                    color: '#EAEAEA'
        logo:
            quality: 100
            filters:
                thumbnail:
                    size:
                        - 250
                        - 200
                    mode: inset
        logo_large:
            quality: 100
            filters:
                thumbnail:
                    size:
                        - 600
                        - 200
                    mode: inset
        main_image:
            quality: 100
            filters:
                thumbnail:
                    size:
                        - 800
                        - 600
                    mode: outbound
        leaderboard:
            quality: 100
            filters:
                thumbnail:
                    size:
                        - 728
                        - 90
                    mode: inset
                background:
                    size:
                        - 728
                        - 90
                    color: '#EAEAEA'
        largebanner:
            quality: 100
            filters:
                thumbnail:
                    size:
                        - 320
                        - 100
                    mode: inset
                background:
                    size:
                        - 320
                        - 100
                    color: '#EAEAEA'
        square:
            quality: 100
            filters:
                thumbnail:
                    size:
                        - 250
                        - 250
                    mode: inset
                background:
                    size:
                        - 250
                        - 250
                    color: '#EAEAEA'
        wideskyscrapper:
                  quality: 100
                  filters:
                      thumbnail:
                          size:
                              - 160
                              - 600
                          mode: inset
                      background:
                          size:
                              - 160
                              - 600
                          color: '#EAEAEA'

gregwar_captcha:
    quality: 100
    width: 150
    height: 40
    length: 6
    distortion: false
    background_color: [255,255,255]

ewz_recaptcha:
    public_key: ~
    private_key: ~
