parameters:
    api_tokens: null
    api_pin: null
multi_domain:
    hosts:
        danceevents.ca:
            id: 1
            path: custom/domain/
            template: default
            locale: en-us
            database: dance_domain1
            elastic: danceevents
            title: 'Dance Events'
            branded: 'on'
