<?php

namespace ArcaSolutions\ArticleBundle\Repository;

use ArcaSolutions\CoreBundle\Repository\EntityCategoryRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * Articlecategory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlecategoryRepository extends EntityCategoryRepository
{
    /**
     * ArticlecategoryRepository constructor.
     * Sets active items field
     *
     * @param EntityManager $em
     * @param ClassMetadata $class
     */
    public function __construct(EntityManager $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);

    }

    /**
     * {@inheritdoc}
     */
    public function getParentCategories($limit = null, $featured = true)
    {
        $this->setMaxItems($limit);

        return parent::getParentCategories($featured);
    }
}
