<?php

namespace ArcaSolutions\ReportsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReportEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportEventRepository extends EntityRepository
{
}
