<?php

namespace ArcaSolutions\ReportsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReportPostDailyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportPostDailyRepository extends EntityRepository
{
}
