editAreaLoader.lang["tr"]={
new_document: "yeni bir boş belge",
search_button: "arama ve değiştirme",
search_command: "açık / sonraki arama bölgede arama",
search: "arama",
replace: "değiştirmek",
replace_command: "arama alanı açmak / değiştirin",
find_next: "sonraki bulmak",
replace_all: "tüm yerine",
reg_exp: "düzenli ifadeler",
match_case: "harf eşleştir",
not_found: "bulunamadı.",
occurrence_replaced: "değişiklik yapıldı.",
search_field_empty: "Alan boş ara",
restart_search_at_begin: "Alanının sonuna ulaşıldı. Başındaki yeniden başlatın.",
move_popup: "Arama açılan hareket",
font_size: "--Yazı boyutu--",
go_to_line: "satırına gidin",
go_to_line_prompt: "satır numarasını gidin:",
undo: "geri",
redo: "yeniden yapmak",
change_smooth_selection: "bazı ekran özellikleri (akıllı ekran fakat daha fazla CPU şarj) aktif / pasif",
highlight: "açık / kapalı geçiş sözdizimi vurgulamak",
reset_highlight: "(metinden uyumsuz ise) vurgulamak sıfırlamak",
word_wrap: "sözcük kaydırma modu arasında geçiş",
help: "hakkında",
save: "kurtarmak",
load: "yük",
line_abbr: "Ln",
char_abbr: "Ch",
position: "Pozisyon",
total: "Toplam",
close_popup: "Popup kapatın",
shortcuts: "Kısayollar",
add_tab: "metne tablolama ekleyin",
remove_tab: "metin tablolama kaldırmak",
about_notice: "Uyarı: sözdizimi vurgulamak işlevi sadece küçük metin için",
toggle: "Editör değiştirir",
accesskey: "Accesskey",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Işleme...",
fullscreen: "tam ekran",
syntax_selection: "--Sözdizimi--",
close_tab: "Kapat dosya"
};
