parameters:
    article.renewal.period: '1'
    article.renewal.unit: 'Y'
    authorize.login: ''
    authorize.recurring.length: 1
    authorize.recurring: 'off'
    authorize.status: 'off'
    authorize.txnkey: ''
    banner.renewal.period: '1'
    banner.renewal.unit: 'Y'
    classified.renewal.period: '1'
    classified.renewal.unit: D
    event.renewal.period: '1'
    event.renewal.unit: M
    listing.renewal.period: '1'
    listing.renewal.unit: 'Y'
    pagseguro.email: ''
    pagseguro.status: 'off'
    pagseguro.token: ''
    payflow.login: ''
    payflow.partner: ''
    payflow.status: 'off'
    payment.currency_symbol: R$
    payment.invoice_payment: 'on'
    payment.manual_payment: 'on'
    payment.payment_currency: BRL
    paypal.account: ''
    paypal.recurring.cycle: 1
    paypal.recurring.times: 0
    paypal.recurring.unit: M
    paypal.recurring: 'off'
    paypal.status: 'off'
    paypalapi.password: ''
    paypalapi.signature: ''
    paypalapi.status: 'off'
    paypalapi.username: ''
    twocheckout.login: ''
    twocheckout.status: 'off'
    worldpay.instid: ''
    worldpay.status: 'off'
