<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo '"Listing Title (Required)","Listing SEO Title","Listing Email","Listing URL","Listing Address","Listing Address2","Listing Country","Listing Country Abbreviation","Listing Region","Listing Region Abbreviation","Listing State","Listing State Abbreviation","Listing City","Listing City Abbreviation","Listing Neighborhood","Listing Neighborhood Abbreviation","Listing Postal Code","Listing Latitude","Listing Longitude","Listing Phone","Listing Fax","Listing Short Description","Listing Long Description","Listing SEO Description","Listing Keywords","Listing Renewal Date","Listing Status","Listing Level","Listing Category 1","Listing Category 2","Listing Category 3","Listing Category 4","Listing Category 5","Listing Template","Listing DB Id","Custom ID","Account Username","Account Password","Account Contact First Name","Account Contact Last Name","Account Contact Company","Account Contact Address","Account Contact Address2","Account Contact Country","Account Contact State","Account Contact City","Account Contact Postal Code","Account Contact Phone","Account Contact Fax","Account Contact Email","Account Contact URL"
';
	echo '"Bees Knees Dance","Bees Knees Dance","info@beeskneesdance.com","http://beeskneesdance.com","805 Dovercourt Road, Toronto ON",,,,,,,,,,,,"M6H 2X4","43.662778","-79.429509","(647) 478-9682",,,"Named for the popular 1920s slang, Bees’ Knees Dance strives to embody the impressive standard from which our moniker was derived. The compliment was often bestowed on those deemed terrific dancers and we believe the expression can apply to absolutely anyone.Founded in 1999 by notable Toronto dancer Mandi Gould, Bees’ Knees Dance is now thriving under an enthusiastic collective of the studio’s instructors. Boasting decades of combined experience, members of the core team have trained with some of the world’s best across North America and Europe and compete and perform internationally with the Bees’ Knees Dance professional troupe, That Swing!.Classes with Bees’ Knees Dance are innovative, relaxed, and infectious, providing individual attention to each student and appealing to beginner and experienced dancers alike. We offer classes in Lindy Hop, Charleston, Balboa, Cane Tricks and Authentic Solo Jazz and Tap, and proudly offer the Bees’ Knees Tease to allow folks to try us out before committing to a full month program.Swing dancing in Toronto is so much more than a collection of steps − It’s joining a welcoming and supportive community; it’s building new relationships and colourful memories; it’s unleashing renewed confidence and limitless potential; it’s discovering live music so infectious, the rhythm reigns; and it’s the exhilaration of finding Toronto’s best kept secret brimming with joy, inclusivity, creativity and physical expression.",,,,"active","diamond","Ballet","Ballroom",,,,"Listing","1",,,,,,,,,,,,,,,,
';
	echo '"æByfield Dance Experience","æByfield Dance Experience",,"http://bdxstudio.com","819 Yonge Street",,,,,,,,,,,,"æM4W 2G9","43.672606","-79.387482","(416) 917-1169",,,,,"hip hop || tap || adults",,"active","gold",,,,,,,"2",,,,,,,,,,,,,,,,
';
	echo '"æEsmeralda Enrique Spanish Dance Company","æEsmeralda Enrique Spanish Dance Company","academy@flamencos.net","http://www.flamencos.net","401 Richmond Street West",,,,,,,,,,,,"M5V 3A8","43.647884","-79.394823","(416) 595-5753",,,,,"adults || flamenko",,"active","gold",,,,,,,"3",,,,,,,,,,,,,,,,
';
	echo '"Advanced School of Music and Dance","Advanced School of Music and Dance","info@privatemusiclessons.ca","http://privatemusiclessons.ca","3030 Don Mills Road E","Lower Level, Unit 23",,,,,,,,,,,"M2J 2T9","43.785944","-79.35265","(416) 410-4397",,,,,"Belly Dance || Acro || Ballet || Birthday party || Kids || Hip hop || Jazz || Bollywood",,"active","gold","Ballet",,,,,,"4",,,,,,,,,,,,,,,,
';
	echo '"Afro-Latino Dance Company","Afro-Latino Dance Company","info@afrolatinodc.com","http://www.afrolatinodc.com","901 Yonge St, Toronto, ON ","Lower level",,,,,,,,,,,"M4W 2H2","43.674819","-79.388308","(416) 671-7140","(416) 503-0278",,,,"kizomba || bachata || reggaeton || salsa || rumba || cuban salsa",,"active","gold","National dance -> Afrocuban","Bachata","Kizomba","Latin","Performances",,"5",,,,,,,,,,,,,,,,
';
	echo '"Arabesque Academy","Arabesque","info@arabesquecanada.com","http://arabesquecanada.com","1397 Yonge St, Toronto, ON","2nd floor",,,,,,,,,,," M4T 1Y4","43.687077","-79.393455","(416) 920-5593",,,,,"Arabesque || adults || folk",,"active","gold","Arabesque","Performances",,,,,"6",,,,,,,,,,,,,,,,
';
	echo '"Arthur Murray","Arthur Murray","info@arthurmurraynorthyork.com","http://www.arthurmurraynorthyork.com","7-27 Rean Dr, Toronto, ON ","Units 7 & 8",,,,,,,,,,,"M2K 0A6","43.767687","-79.382264","(416) 479-4225",,,,,"latin || swing || adults || rumba || merengue",,"active","gold","Adults","Private lessons","Wedding dance lessons",,,,"7",,,,,,,,,,,,,,,,
';
	echo '"Canada\\'s National Ballet School","Canadas National Ballet School",,"http://www.nbs-enb.ca","400 Jarvis St, Toronto, ON",,,,,,,,,,,,"M4Y 2G6","43.664004","-79.377724","(416) 964-3780","(416) 964-5133",,,,"adults ballet",,"active","gold","Adults","Ballet","Kids & Teens","Rentals",,,"8",,,,,,,,,,,,,,,,
';
	echo '"Barre Nouvelle Fitness and Dance","Barre Nouvelle Fitness and Dance","info@barrenouvelle.com","http://www.barrenouvelle.com","140 La Rose Avenue","Unit 201 ",,,,,,,,,,,"M9P 1B1","43.684962","-79.523981","(416) 245-7070",,,,,"creative moment || zumba || ballet",,"active","gold","Kids & Teens","Adults","Ballet",,,,"9",,,,,,,,,,,,,,,,
';
	echo '"Bayview School of Ballet","Bayview School of Ballet","annakovarsky@bellnet.ca","http://www.bayviewballet.com","148 Willowdale Ave, North York",,,,,,,,,,,,"M2N 4Y4","43.766099","-79.400834","(416) 222-5111",,,,,"adults ballet || pointe || tap || jazz || hip-hop || zumba || Lyrical Contemporary",,"active","gold","Adults","Ballet","Kids & Teens","Professional dance",,,"10",,,,,,,,,,,,,,,,
';
?>
